[package]
name = "bdk_wallet_0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bdk = "0.29.0"
bdk = { version = "0.29.0", features = ["use-esplora-blocking"] }
